#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/board
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/utils.js:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/utils.js
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xdc.tci:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xdc.tci
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/template.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/template.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/om2.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/om2.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xmlgen.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xmlgen.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xmlgen2.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/xmlgen2.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/Warnings.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/Warnings.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/IPackage.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/IPackage.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/package.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/package.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/services/global/Clock.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/services/global/Clock.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/services/global/Trace.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/services/global/Trace.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/bld.js:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/bld.js
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/BuildEnvironment.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/PackageContents.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/PackageContents.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/_gen.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/_gen.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Library.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Library.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Executable.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Executable.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Repository.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Repository.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Configuration.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Configuration.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Script.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Script.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Manifest.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Manifest.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Utils.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/Utils.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget2.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget2.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget3.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITarget3.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/ITargetFilter.xs
/home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/package.xs:
package.mak: /home/gtbldadm/nightlybuilds/repo_manifests/scripts/jenkins/coresdk_rtos_jacinto_08_00_00_37/xdctools_3_61_04_40_core/packages/xdc/bld/package.xs
package.mak: config_mk.bld
package.mak: package.bld
package.mak: src/Module.xs
package.mak: build/buildlib.xs
package.mak: Settings.xdc.xdt
package.mak: utils.xs
endif


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.board.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.board" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.board $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,board_1_0_10_5
ifeq (,$(MK_NOGENDEPS))
-include package/rel/board_1_0_10_5.tar.dep
endif
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: package/package.bld.xml
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: package/build.cfg
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: package/package.xdc.inc
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_ddrtempmonitor.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_control.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_utils.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_lld_init.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_pll.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/J721E_pinmux_data_gesi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_info.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_init.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_clock.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_i2c_io_exp.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_power.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/J721E_pinmux_data_info.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/J721E_pinmux_data.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_pinmux.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_ethernet_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_serdes_cfg.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_mmr.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/J721E_pinmux_data_gesi_cpsw9g.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_ddr.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/board_ddr_prime_dma.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/board.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/sensors/tlc59108.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/sensors/imx390.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/common/common.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/audio/pcm3168A.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/audio/afe8310.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub941.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub924.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub926.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub960.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub953.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub9702.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub925.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/combos/ds90ub9xx_tlc59108.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/combos/ds90ub92x_afe8310.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/pmic/tps62363.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/pmic/tps65941.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/boardStub.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/board_flash.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/hyperflash/nor_hyperflash.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/nor.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_ospi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_spi_patterns.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_spi_phy_tune.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_qspi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_pll.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_ethernet_config.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_utils.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_ddr.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_control.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_ddrRegInit.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_clock.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_internal.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_serdes_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_i2c_io_exp.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_power.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/include/board_pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/J721E_pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/sensors/imx390.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/sensors/tlc59108.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/common/common.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/audio/pcm3168A.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/audio/afe8310.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/board_devices.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub960.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub9702.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub925.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub953.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub926.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub941.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/fpd/ds90ub924.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/combos/ds90ub92x_afe8310.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/combos/ds90ub9xx_tlc59108.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/pmic/tps62363.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/pmic/tps65941.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/include/board_flash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/device/mt25qu512abb.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/device/s71ks512s.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/device/s25fl256s.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/device/m35xu512.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/hyperflash/nor_hyperflash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_ospi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_spi_patterns.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_spi_phy_tune.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/ospi/nor_qspi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/nor/nor.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/j721e_evm/src_files_j721e_evm.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/src_files_starterware.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/devices/src_files_devices.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/flash/src_files_flash.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/src_files_lld.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: config_mk.bld
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: build/makefile.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: board_component.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./lib
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmK2L/src_files_evmK2L.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmAM437x/src_files_evmAM437x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmC6678/src_files_evmC6678.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmC6657/src_files_evmC6657.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmK2H/src_files_evmK2H.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmAM572x/src_files_evmAM572x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/skAM335x/src_files_skAM335x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmAM335x/src_files_evmAM335x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/idkAM572x/src_files_idkAM572x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/idkAM574x/src_files_idkAM574x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmK2E/src_files_evmK2E.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/skAM437x/src_files_skAM437x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/idkAM571x/src_files_idkAM571x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmK2G/src_files_evmK2G.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/icev2AM335x/src_files_icev2AM335x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/idkAM437x/src_files_idkAM437x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmAM571x/src_files_evmAM571x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmOMAPL137/src_files_evmOMAPL137.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/lcdkOMAPL138/src_files_lcdkOMAPL138.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/evmKeystone/src_files_evmKeystone.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: src/bbbAM335x/src_files_bbbAM335x.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./examples/ddr_thermal_test_app/src/main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./examples/ddr_thermal_test_app/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/csirx/src/csirx_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/csirx/src/csirx_display.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/csirx/src/csirx_display.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/csirx/src/csirx_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/csirx/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/display_port/src/display_port_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/display_port/src/display_port_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/display_port/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/src/main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/src/framework.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/src/auto_tests.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/src/framework.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/src/framework_entry.S
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/framework/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/eeprom/src/eeprom_test_v2.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/eeprom/src/eeprom_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/eeprom/src/eeprom_test_v2.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/eeprom/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/leo_pmic_lib/src/leo_pmic_lib_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/leo_pmic_lib/src/leo_pmic_lib_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/leo_pmic_lib/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/lin/src/lin_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/lin/src/lin_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/lin/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/lin/build/j721e_evm/lin_gpio_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/src/eeprom_stress_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/src/boot_eeprom_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/src/eeprom_stress_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/src/boot_eeprom_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_eeprom/build/j721e_evm/boot_eeprom_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hyperbus/src/hyperbus_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hyperbus/src/hyperbus_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hyperbus/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hyperbus/build/j721e_evm/hyperbus_gpio_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/norflash/src/ospi_quad_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/norflash/src/ospi_quad_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/norflash/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/uart_diag.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/am65xx_uart_stress_test_script.ttl
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/am64x_uart_stress_test_script.ttl
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/ReadMe.txt
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/uart_stress_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/src/uart_stress_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/uart/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_tuner_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_common.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_dsi_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_csi_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_dsi_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_tuner_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/src/fpd_csi_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/fpd_lib/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/framework_linker.lds
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/diag_entry_r5.asm
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/diag_common_cfg.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/linker_mpu1_0.lds
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/linker_mcu1_0.lds
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/framework_init.asm
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/framework_linker_r5.lds
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/diag_common_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/common/j721e/diag_entry.asm
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/emmc/src/emmc_main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/emmc/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/clock_generator/src/clock_generator.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/clock_generator/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/temperature/src/temperature_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/temperature/src/temperature_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/temperature/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_switch/src/boot_switch_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_switch/src/boot_switch_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_switch/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/boot_switch/build/j721e_evm/boot_switch_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/led/src/led_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/led/src/led_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/led/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/hdmi_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_hdmi_panel.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/hdmi_test_v2.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_hdmi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_hdmi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_dss_panel.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_dss.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/hdmi_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/hdmi_test_v2.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_hdmi_panel.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/src/evmk2g_dss.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/hdmi/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/create_sd.bat
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsi/src/fpd_dsi_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsi/src/fpd_dsi_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsi/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/src/gpio_test_header.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/src/exp_header_tpr12.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/src/gpio_test_header.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/src/exp_header_tpr12.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/exp_header/build/j721e_evm/gpio_test_header_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mem/src/mem_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mem/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/automation_header/src/automation_header_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/automation_header/src/automation_header_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/automation_header/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/automation_header/build/j721e_evm/automation_header_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/create_sd.sh
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/current_monitor/src/current_monitor_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/current_monitor/src/current_monitor_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/current_monitor/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/current_monitor/build/j721e_evm/current_monitor_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsitx/src/dsitx_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsitx/src/dsitx_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/dsitx/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mcan/src/mcan_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mcan/src/mcan_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mcan/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mcan/build/j721e_evm/GPIO_MCAN_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ospi/src/ospi_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ospi/src/ospi_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ospi/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ospi/build/j721e_evm/ospi_mux_gpio_pin_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/build/board_diag_img.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/board_diag_component.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mmcsd/src/mmcsd_main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/mmcsd/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/adc/src/adc_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/adc/src/adc_test_v2.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/adc/src/adc_test_v2.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/adc/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ext_rtc/src/ext_rtc_test.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ext_rtc/src/ext_rtc_test.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/ext_rtc/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/pmic/src/pmic_test_v2.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/pmic/src/pmic_test_v2.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./diag/pmic/build/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_ddrtempmonitor.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_control.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_utils.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_lld_init.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_pll.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_ethernet_config.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_utils.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_ddr.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_control.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_ddrRegInit.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_clock.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_internal.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_serdes_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_i2c_io_exp.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_power.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/include/board_pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_pll.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/J721E_pinmux_data_gesi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_info.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_init.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_clock.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_i2c_io_exp.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_power.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/J721E_pinmux_data_info.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/j721e_evm_gesi_app_board.pinmux
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/J721E_pinmux_data.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_pinmux.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_ethernet_config.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/src_files_j721e_evm.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_serdes_cfg.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/j721e_evm_gesi_app_board_cpsw9g.pinmux
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_mmr.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/J721E_pinmux_data_gesi_cpsw9g.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_ddr.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/j721e_evm_base_board.pinmux
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/j721e_evm_info_app_board.pinmux
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/J721E_pinmux.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/j721e_evm/board_ddr_prime_dma.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/board.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/src_files_starterware.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/src_files_devices.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/sensors/tlc59108.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/sensors/imx390.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/sensors/imx390.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/sensors/tlc59108.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/common/common.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/common/common.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/audio/pcm3168A.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/audio/pcm3168A.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/audio/afe8310.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/audio/afe8310.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/board_devices.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub960.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub9702.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub941.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub924.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub926.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub960.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub925.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub953.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub953.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub9702.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub925.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub926.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub941.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/fpd/ds90ub924.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/combos/ds90ub92x_afe8310.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/combos/ds90ub9xx_tlc59108.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/combos/ds90ub9xx_tlc59108.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/combos/ds90ub92x_afe8310.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/pmic/tps62363.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/pmic/tps62363.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/pmic/tps65941.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/devices/pmic/tps65941.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/Module.xs
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/boardStub.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/include/board_flash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/src_files_flash.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/board_flash.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/device/mt25qu512abb.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/device/s71ks512s.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/device/s25fl256s.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/device/m35xu512.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/hyperflash/nor_hyperflash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/hyperflash/nor_hyperflash.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/nor.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_ospi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_spi_patterns.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_ospi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_spi_patterns.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_spi_phy_tune.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_qspi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_spi_phy_tune.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_spi_patterns.bin
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/ospi/nor_qspi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/flash/nor/nor.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./src/src_files_lld.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./.xdcenv.mak
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./board_component.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./Settings.xdc.xdt
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./board_cfg.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./package.bld
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils.xs
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./package.xdc
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./package.xs
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./config_mk.bld
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./board.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/host/include/ProcessorSDKSerialFlash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/host/source/main.cpp
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/host/source/ProcessorSDKSerialFlash.cpp
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/host/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/host/setenv.bat
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/spi/spi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/spi/spi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/emmc/emmc.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/emmc/emmc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/uart_main.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/qspi/qspi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/qspi/qspi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/hyperflash/hyperflash.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/hyperflash/hyperflash.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/xmodem.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/ospi/ospi.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/src/ospi/ospi.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/include/xmodem.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/include/flash_programmer.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/makefile
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/board/src/board.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/soc.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/tpr12/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/tpr12/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am437x/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am437x/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/linker_j7.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/linker_am64x.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/ufp_misc.asm
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/soc_k3.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/linker_am65xx.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k3/ufp_init.asm
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am335x/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am335x/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am335x/soc_platform_pll.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am335x/soc_platform_pll.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k2g/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k2g/init.S
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k2g/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k2g/a15.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/k2g/a15.h
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/awr294x/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/awr294x/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am57xx/linker.cmd
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/soc/am57xx/soc.c
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/uniflash/target/build/uart_make.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./utils/board_utils_component.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./Settings.xdc
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./package.mak
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./build/buildlib.xs
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: ./build/makefile.mk
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/board_1_0_10_5/ti/board/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

./packages/board_1_0_10_5.tar: package/rel/board_1_0_10_5.xdc.inc package/rel/board_1_0_10_5/ti/board/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/board_1_0_10_5.xdc.inc,package/rel/board_1_0_10_5.tar.dep)


release release,board_1_0_10_5: all ./packages/board_1_0_10_5.tar
clean:: .clean
	-$(RM) ./packages/board_1_0_10_5.tar
	-$(RM) package/rel/board_1_0_10_5.xdc.inc
	-$(RM) package/rel/board_1_0_10_5.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard packages))
    $(shell $(MKDIR) packages)
endif
endif
clean::
	-$(RMDIR) package


